services:
  owasp-zap:
    image: ghcr.io/zaproxy/zaproxy:latest
    container_name: owasp-zap
    volumes:
      - ./reports:/app/reports
    ports:
      - "8080:8080"
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8080
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
    networks:
      - zapnet
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: zap-api-flask
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=api_flask.py
      - FLASK_ENV=development
    networks:
      - zapnet
    depends_on:
      owasp-zap:
        condition: service_healthy

    
  web:
    build:
      context: ./nginx-web
      dockerfile: Dockerfile
    container_name: zap-web-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - zapnet
    
networks:
  zapnet:
    driver: bridge